### PR TITLE
Fix gnome 44 compatibility

### PR DESCRIPTION
**Pull request by PapyElGringo**
Fix some changes from gnome 44 that make the extension crash on login @expeehaa

### CODE REVIEW

**Comment by themr0c** [comment]
I tested it successfully on Fedora 38 with Gnome 44.

Before this update, Material Shell was crashing on startup. After each login, I had to: uninstall the extension, restart Xorg, reinstall and enable the extension. I could reproduce the crash by restarting Xorg.

With this update, I could restart Xorg without any problems: the Material Shell extension loaded again as expected.

Thank you for this, and for the extension in general!

**Review by themr0c — APPROVED** [review]

**Comment by PapyElGringo** [comment]
@themr0c Thanks for testing it !

**Comment by themr0c** [comment]
When do you plan to publish the next release?

**Comment by PapyElGringo** [comment]
It's currently waiting for gnome validation

**Pull request merged**
