### PR TITLE
Fix titlebar visibility on gnome44+

### PR DESCRIPTION
**Pull request by PapyElGringo**
Fix xlib api change on recent version

### CODE REVIEW

**Review by HalfVoxel — APPROVED** [review]
_MOTIF_WM_HINTS = 0 seems to be documented as showing no decorations at all.
I'd like to see a source (ideally included as a comment) for where the new value comes from.

**Comment by PapyElGringo** [comment]
It's seems that removing only the titlebar doesn't work and it's needed to remove all the decoration. But since we are doing it only on maximized window it's fine. The value come from the research of other users in issue https://github.com/material-shell/material-shell/issues/964

**Comment by HalfVoxel** [comment]
Does setting it to zero also work in earlier versions of gnome?

**Comment by PapyElGringo** [comment]
> Does setting it to zero also work in earlier versions of gnome?

Probably but can't really test it :(

**Comment by HalfVoxel** [comment]
I'd be nicer without the version check.
WM_HINTs=2 is a border around the window. I haven't really seen this border at all, and I don't think we'd want one anyway. So maybe try removing it also for earlier versions.

**Comment by PapyElGringo** [comment]
Yeah done

**Pull request merged**
