### PR TITLE
Disable changing menu on hover another item

### PR DESCRIPTION
**Pull request by MartinPL**

### CODE REVIEW

**Comment by PapyElGringo** [comment]
Not sure to get what you want to do

**Comment by MartinPL** [comment]
Sorry I forgot to add description. This disabled annoying gnome shell behavior (imo): when you open some menu for example notification area and you hover on another items it will change to this new item.

**Comment by JonasLoos** [comment]
I prefer the default behaviour, so I'd suggest to add it as an option (if at all). Maybe this "feature" better belongs in a separate extension.

**Comment by MartinPL** [comment]
Yes, separate extension sounds good since it anway don't depends on MS.

**Pull request closed without merging**
